# Analisis de Datos con Python - Clase 3

[Material Complementario](https://1drv.ms/f/s!Anh5cvrOJtUTlPZnUCQ9UDEpjh1Gtg?e=P6Qlu9)

In [5]:
![image](numpy.png) 

"[image]" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [8]:
import numpy as np

# MODULO 3 - Biblioteca Numpy 1
Numpy (de Numerical Python) es la principal librería de  cálculo numérico de Python y el ecosistema de librerías  científicas del lenguaje (como Pandas y Matplotlib)  recurre a Numpy para realizar sus operaciones.    
Se basa en una estructura de datos multidimensional  llamada **array** y en una serie de funciones muy  optimizadas para su manipulación, incluyendo  operaciones matemáticas, lógicas, de selección y  ordenamiento, operaciones estadísticas, álgebra lineal  y más.

# 1.1. Array
El array (o ndarray) es la estructura que permite  acelerar las operaciones matemáticas en Python, sin  la necesidad de recurrir a bucles para operar con  todos sus elementos, lo que se llama **vectorización**.     
El array es una estructura de datos mucho más  optimizada que la lista, pero a cambio presenta  menos flexibilidad.     
El array sólo admite elementos  de un **único tipo de dato** y **no se puede cambiar la  cantidad de elementos**.     
Esto garantiza que siempre  ocupe el mismo espacio y todos sus elementos se  puedan representar en una sección continua de  memoria.    
Es una estructura multidimensional, por lo que  permite representar vectores, matrices o arreglos  de más dimensiones.

### 1.1.1. Atributos de un Array
- **dtype**: el tipo de dato del array, en general numérico.
- **size**: cantidad de elementos.
- **nbytes**: total de bytes consumidos por los datos  (bytes del tipo de dato por la cantidada de elementos).
- **ndim**: número de dimensiones.
- **shape**: cantidad de elementos en cada dimensión.

In [10]:
a = np.array([1, 2, 3])
print(type(a))
a.dtype

<class 'numpy.ndarray'>


dtype('int32')

In [12]:
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b)
# Obtenemos la transposicion de b
print(b.T)

# Cantidad de elementos
print(a.size)
print(b.size)

# Cuantos bytes hay en a y b
print(a.nbytes)
print(b.nbytes)

# Tipos de datos
print(a.dtype)
print(b.dtype)

# Tipos de shape(filas, columnas)
print(a.shape)
print(b.shape)


# Dimension 
print(a.ndim)
print(b.ndim)

[[4 5 6]
 [7 8 9]]
[[4 7]
 [5 8]
 [6 9]]
3
6
12
24
int32
int32
(3,)
(2, 3)
1
2


### 1.1.2. Creacion de un Array
Hay muchas formas de crear arrays. A través de la función **np.array**  se pueden usar secuencias como listas (que pueden estar anidadas  para representar arreglos multidimensionales). Podemos pasar el  parámetro dtype para forzar a representar los datos en un tipo  determinado. Si no se pasa, la función tratará de inferirlo.

In [13]:
arr1 =np.array([1,2,3,4,5])
print(arr1, arr1.dtype, arr1.nbytes)
print('_________________________________')
arr2 =np.array([1,2,3,4,5], dtype = np.float64)
print(arr2, arr2.dtype, arr2.nbytes)
print('_________________________________')
arr3 =np.array([1,2,3,4,5], dtype = np.int8)
print(arr3, arr3.dtype, arr3.nbytes)

[1 2 3 4 5] int32 20
_________________________________
[1. 2. 3. 4. 5.] float64 40
_________________________________
[1 2 3 4 5] int8 5


Podemos armar un array de dos dimensiones con listas anidadas,  siempre y cuando todas tengan la misma cantidad de elementos.

In [14]:
arr = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])
print(arr)
print('ndim:', arr.ndim, '- shape:', arr.shape)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndim: 2 - shape: (3, 4)


Además hay numerosas funciones para crear arrays:
- **arange** y **linspace** para rangos de números equiespaciados.
- **zeros**, **ones** y **full** para arrays de cualquier dimensión y forma.
- **identity**, **eye** y **diagonal** para arrays de 2 dimensiones.    
El módulo **random** permite crear arrays con distintas  distribuciones de números al azar.
Las funciones loadtxt y genfromtxt permiten leer archivos de  texto tipo csv.
Tener en cuenta especificar el tipo de dato y el shape cuando sea  necesario.

In [15]:
# zeros
# El dtype es float64 por defecto, pero puede ser asignado con cualquier tipo de datos en NumPy.
#np.zeros(5)
#np.zeros((5), dtype=int)
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
# Ones
# El dtype es float64 por defecto, pero puede ser asignado con cualquier tipo de datos en NumPy.
np.ones(5)
np.ones((5), dtype=int)
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# np.arange
np.arange(10)
np.arange(6,20,2)

array([ 6,  8, 10, 12, 14, 16, 18])

In [19]:
# np.full
np.full((4, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
np.random.randint(5, size=(2, 4))

array([[4, 4, 2, 4],
       [4, 1, 0, 1]])